version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - muezzin_network

  # Kafka Service
  kafka:
    image: apache/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - muezzin_network

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - muezzin_network

  # Kibana Service (for Elasticsearch UI)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - muezzin_network
  
  retriever:
    build:
      context: ./src/retriever 
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOST=
      - GROUP_ID=
      - DIR_PATH=
      - EXPORT_TOPIC=
      - ES_HOST=
    volumes:
      - muezzin_volume:/data
    networks:
      - muezzin_network

  transcriber:
    build:
      context: ./src/transcriber
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOST=
      - GROUP_ID=
      - IMPORT_TOPIC=
      - EXPORT_TOPIC=
      - ES_HOST=
    volumes:
      - muezzin_volume:/data
    networks:
      - muezzin_network
  enricher:
    build:
      context: ./src/enricher
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOST=
      - GROUP_ID=
      - EXPORT_TOPIC=
      - IMPORT_TOPIC=
      - ES_HOST=
    volumes:
      - muezzin_volume:/data
    networks:
      - muezzin_network
  persister:
    build:
      context: ./src/enricher
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOST=
      - GROUP_ID=
      - MONGO_HOST=
      - MONGO_NAME=
      - MONGO_COLL=
      - IMPORT_TOPIC=
      - ES_HOST=
    volumes:
      - muezzin_volume:/data
    networks:
      - muezzin_network

volumes:
  kafka_data:
  es_data:
  mongo_data:
  muezzin_volume:

networks:
  muezzin_network:
    driver: bridge